{{ if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccount | default (include "metallb-bounce.fullname" .) }}
  labels:
    app: {{ include "metallb-bounce.name" . }}
    chart: {{ include "metallb-bounce.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end -}}
